# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'browser.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 612)
        MainWindow.setStyleSheet("background-color: rgb(81, 81, 81);\n"
"color: white;\n"
"font-size: 30px;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(260, 0, 201, 51))
        self.label.setStyleSheet("color: rgb(255, 0, 0);")
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(70, 210, 651, 61))
        self.textEdit.setStyleSheet("background-color: rgb(223, 223, 223);\n"
"color: gray;\n"
"font-size: 40px;\n"
"border-radius: 10px;")
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(300, 280, 171, 61))
        self.pushButton.setStyleSheet("background-color: rgb(0, 191, 191);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 10, 201, 81))
        self.pushButton_2.setStyleSheet("background-color: rgb(218, 145, 0);\n"
"font-size: 30px;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.YandexButton = QtWidgets.QPushButton(self.centralwidget)
        self.YandexButton.setGeometry(QtCore.QRect(580, 60, 191, 41))
        self.YandexButton.setStyleSheet("background-color: rgb(252, 63, 29);\n"
"")
        self.YandexButton.setObjectName("YandexButton")
        self.GoogleButton = QtWidgets.QPushButton(self.centralwidget)
        self.GoogleButton.setGeometry(QtCore.QRect(580, 110, 191, 41))
        self.GoogleButton.setStyleSheet("background-color: rgb(152, 152, 152);\n"
"")
        self.GoogleButton.setObjectName("GoogleButton")
        self.BingButton = QtWidgets.QPushButton(self.centralwidget)
        self.BingButton.setGeometry(QtCore.QRect(580, 160, 191, 41))
        self.BingButton.setStyleSheet("background-color: rgb(76, 220, 167);\n"
"")
        self.BingButton.setObjectName("BingButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 510, 201, 41))
        self.label_2.setObjectName("label_2")
        self.src_sys_label = QtWidgets.QLabel(self.centralwidget)
        self.src_sys_label.setGeometry(QtCore.QRect(220, 510, 151, 41))
        self.src_sys_label.setStyleSheet("color: red;")
        self.src_sys_label.setText("")
        self.src_sys_label.setObjectName("src_sys_label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(580, 10, 201, 41))
        self.label_3.setStyleSheet("color: red;")
        self.label_3.setObjectName("label_3")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(70, 350, 651, 61))
        self.textEdit_2.setStyleSheet("background-color: rgb(223, 223, 223);\n"
"color: gray;\n"
"font-size: 40px;\n"
"border-radius: 10px;")
        self.textEdit_2.setObjectName("textEdit_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(290, 420, 171, 61))
        self.pushButton_3.setStyleSheet("background-color: rgb(0, 191, 191);")
        self.pushButton_3.setObjectName("pushButton_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "browser"))
        self.label.setText(_translate("MainWindow", "f0rk1l browser"))
        self.textEdit.setPlaceholderText(_translate("MainWindow", "search..."))
        self.pushButton.setText(_translate("MainWindow", "Search"))
        self.pushButton_2.setText(_translate("MainWindow", "Show history"))
        self.YandexButton.setText(_translate("MainWindow", "Yandex"))
        self.GoogleButton.setText(_translate("MainWindow", "Google"))
        self.BingButton.setText(_translate("MainWindow", "Bing"))
        self.label_2.setText(_translate("MainWindow", "Search system:"))
        self.label_3.setText(_translate("MainWindow", "Search Engine"))
        self.textEdit_2.setPlaceholderText(_translate("MainWindow", "open link..."))
        self.pushButton_3.setText(_translate("MainWindow", "Open"))
